apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: default
      defaultDatabase: flechtwerk
    secureJsonData:
      password: ""
